# -*- coding: utf-8 -*-
"""Proyecto Entregable 1 - Oviedo, Rocío

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tGtaKdY200DlldUAbOk5CNQw6d7NoWEl
"""

import random

def jugar_adivina_la_palabra():
  palabras = ['amarillo', 'azul', 'blanco', 'gris', 'casa', 'cielo', 'claro', 'color', 'comida', 'correr',
    'corto', 'creer', 'cruzar', 'cuadro', 'cuerpo', 'dama', 'dado', 'dulce', 'edad', 'elefante',
    'empezar', 'encontrar', 'entender', 'escalar', 'escribir', 'espacio', 'esperar', 'estrella', 'estudiar', 'feliz',
    'flor', 'frutilla', 'fruta', 'fuego', 'gato', 'girar', 'grande', 'gelatina', 'guitarra', 'hablar',
    'hacer', 'hermano', 'hijo', 'historia', 'hora', 'huevo', 'idea', 'igual', 'jugar', 'largo',
    'leer', 'libro', 'luz', 'madre', 'mano', 'mar', 'mesa', 'mirar', 'mover', 'mujer',
    'naranja', 'negro', 'nueve', 'nube', 'ojo', 'oso', 'padre', 'piso', 'palabra', 'papel',
    'parar', 'paso', 'paz', 'pozo', 'perro', 'pez', 'pie', 'piedra', 'pintar', 'plata',
    'poder', 'pollo', 'prueba', 'punto', 'querer', 'roto', 'risa', 'reloj', 'rojo', 'rosa',
    'saber', 'sal', 'saltar', 'sentir', 'ser', 'silla', 'sol', 'sonreir', 'suave', 'subir',
    'taza', 'termo', 'temprano', 'tiempo', 'tigre', 'tomar', 'toro', 'trabajar', 'tres', 'ver',
    'verde', 'viaje', 'volar', 'volver', 'zapato', 'zorro', 'abrir', 'aceite', 'agua', 'alto',
    'amigo', 'animal', 'dinosaurio', 'arena', 'bajo', 'boca', 'brazo', 'cabeza', 'calor', 'cama',
    'campo', 'carne', 'ciudad', 'clase', 'clave', 'cocina', 'comer', 'copa', 'carro', 'cuerda',
    'dormir', 'duro', 'escuela', 'familia', 'fiesta', 'flaco', 'fuerza', 'gafas', 'gente', 'gracias',
    'hambre', 'hombre', 'invierno', 'foto', 'joven', 'juego', 'lago', 'lento', 'libre', 'llave',
    'lluvia', 'luna', 'madera', 'manzana', 'mariposa', 'mes', 'mono', 'mesa', 'nadar', 'nieve',
    'nuevo', 'oro', 'pan', 'pelo', 'piedra', 'piel', 'pluma', 'puerta', 'queso', 'rata',
    'ropa', 'sopa', 'tigre', 'torta', 'vaca', 'viento', 'vino', 'vivir', 'yerba', 'zumo']
  palabra_correcta = random.choice(palabras)
  palabra_adivinada = ['_'] * len(palabra_correcta)
  numero_intentos = 5
  intentos = 0
  letras_incorrectas = []

  print(f"¡Hola! Bienvenidx al juego 'Adiviná la palabra' ¿Listx para empezar?\nIngresa una letra: {'_ _'.join(palabra_adivinada)}")
  print(f" Vidas restantes: {numero_intentos - intentos}")
  print(f" Letras incorrectas: {', '.join(letras_incorrectas)}\n")

  while '_' in palabra_adivinada and intentos < numero_intentos:
      letra = input("Ingresa una letra: ").lower()
      if letra.isalpha() and len(letra) == 1:
        if letra in palabra_correcta:
          for i in range(len(palabra_correcta)):
            if palabra_correcta[i] == letra:
                palabra_adivinada[i] = letra
          print(f"¡Bien hecho! Letra correcta. Palabra actual: {' '.join(palabra_adivinada)}")
        else:
          intentos += 1
          letras_incorrectas.append(letra)
          print(f"¡Ups! La letra que ingresaste no es correcta. Te quedan {numero_intentos - intentos} vidas")
          print(f"Letras incorrectas: {', '.join(letras_incorrectas)}\n")
      else:
          print("Por favor, ingresá una letra válida.\n")
  if '_' not in palabra_adivinada:
    print(f"¡Felicitaciones! ¡Ganaste!")
  else:
    print(f"¡Ups! Se acabaron los intentos. La palabra secreta era '{palabra_correcta}'")

if __name__ == "__main__":
  jugar_adivina_la_palabra()